{"name": "Получение заказов неавторизованным пользователем", "status": "passed", "description": "Тест проверяет, что неавторизованный пользователь не может получить список заказов и получает ошибку", "start": 1717347277642, "stop": 1717347278290, "uuid": "51a924da-b86e-4182-83ca-5e42f9d26532", "historyId": "c53dd8e79ba985211f67319f8d7b949c", "testCaseId": "c53dd8e79ba985211f67319f8d7b949c", "fullName": "tests.test_receive_user_orders.TestReceiveUserOrders#test_unauthorized_user_cannot_get_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receive_user_orders"}, {"name": "subSuite", "value": "TestReceiveUserOrders"}, {"name": "host", "value": "DESKTOP-212965U"}, {"name": "thread", "value": "10096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receive_user_orders"}]}